spring.datasource.url=jdbc:mysql://localhost:3306/worldcuppredictor26
spring.datasource.username=root
spring.datasource.password=Agyengo.gh123

spring.mail.username=fagyemang390@gmail.com
spring.mail.password=fbzoupdnleqlwqyy

server.port=8091